on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  before_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List repository contents
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check configs
        run: |
          echo "Checking environment variables..."
          echo "X_API_URL: $X_API_URL"
          echo "CONTACT_USER: $CONTACT_USER"

  install_dependencies:
    runs-on: ubuntu-latest
    needs: before_script

    steps:
      - name: Install dependencies
        run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: [before_script, install_dependencies]

    steps:
      - name: Print working directory
        run: pwd

      - name: List repository contents
        run: ls -la

      - name: Build project
        env: 
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_HOST: ${{ secrets.X_API_HOST }}
          CONTACT_USER: ${{ secrets.CONTACT_USER }}
          CONTACT_KEY:  ${{ secrets.CONTACT_KEY }}
        run: |
          echo "Starting build process..."
          yarn build --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: [before_script, build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          S3_BUCKET: ${{ secrets.S3_BUCKET}}
        run: |
          aws s3 sync ./build s3://$S3_BUCKET --delete
