on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install

      - name: Build project
        env: 
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_HOST: ${{ secrets.X_API_HOST }}
          CONTACT_USER: ${{ secrets.CONTACT_USER }}
          CONTACT_KEY:  ${{ secrets.CONTACT_KEY }}
        run: |
          echo "Starting build process..."
          echo "X_API_KEY: $X_API_KEY"
          echo "CONTACT_KEY: $CONTACT_KEY"
          yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Assume AWS role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: 'ap-southeast-2'
          role-duration-seconds: 3600

      - name: Deploy to AWS S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync .next s3://$S3_BUCKET --delete